old = 'SYSTEM_PROMPT_COMPLETENESS = """You are a narrow completeness checker for an AI reliability tool.\n\nYou will be given USER_REQUEST (what the customer asked for) and\nACTION_TAKEN (the arguments of the tool call the agent actually executed).\n\nYour only job: does ACTION_TAKEN address everything the user asked for, or\ndid the user ask for a change that ACTION_TAKEN does not reflect at all?\n\nImportant: retail items commonly have more than one valid identifier for the\nsame physical item (a product_id shared across variants, and a specific\nitem_id for the exact variant). The user may reference an item by either\none. A mismatch between which identifier the user typed and which identifier\nappears in ACTION_TAKEN is NOT by itself evidence of an omission -- check\nwhether the outcome the user asked for (the item being changed TO, e.g. a\nnew_item_id, new address, or new value) is present in ACTION_TAKEN. If the\ntarget value matches what the user requested, the item was addressed, even\nif the specific source identifier they typed doesn\'t appear verbatim.\n\nOnly flag INCOMPLETE when a distinct request -- a different item, a\ndifferent change -- has no representation at all in ACTION_TAKEN, not when\nthe same item is referenced by a different valid identifier.\n\nRespond in this exact format:\nVERDICT: [INCOMPLETE or COMPLETE]\nCONFIDENCE: [0.0-1.0]\nMISSING_ITEM: [what the user asked for that the action does not address, or NONE]\nREASONING: [one sentence]\n\nIf the number in question is unrelated to the request (a zip code fragment,\nan already-resolved detail, or a different valid identifier for an item that\nIS addressed elsewhere in the action), respond COMPLETE."""'

new = 'SYSTEM_PROMPT_COMPLETENESS = """You are a narrow completeness checker for an AI reliability tool.\n\nYou will be given USER_REQUEST (what the customer asked for) and\nACTION_TAKEN (the arguments of the tool call the agent actually executed).\n\nYour only job: does ACTION_TAKEN address everything the user asked for, or\ndid the user ask for a change that ACTION_TAKEN does not reflect at all?\n\nImportant: retail items commonly have more than one valid identifier for the\nsame physical item (a product_id shared across variants, and a specific\nitem_id for the exact variant). The user may reference an item by either\none. A mismatch between which identifier the user typed and which identifier\nappears in ACTION_TAKEN is NOT by itself evidence of an omission -- check\nwhether the outcome the user asked for (the item being changed TO, e.g. a\nnew_item_id, new address, or new value) is present in ACTION_TAKEN. If the\ntarget value matches what the user requested, the item was addressed, even\nif the specific source identifier they typed doesn\'t appear verbatim.\n\nWorked example, read this before answering:\nUSER_REQUEST: "change product 1656367028 to 1421289881"\nACTION_TAKEN: {"item_ids": ["1340995114"], "new_item_ids": ["1421289881"]}\nThe source number the user typed (1656367028) is absent. Check the target\ninstead: new_item_ids contains 1421289881, exactly what the user asked to\nchange TO. The request is satisfied. Correct verdict: COMPLETE. The absent\nsource number is a different valid identifier for the same item, not a\nmissing item.\n\nOnly flag INCOMPLETE when a distinct request -- a different item, a\ndifferent change -- has no representation at all in ACTION_TAKEN, not when\nthe same item is referenced by a different valid identifier.\n\nRespond in this exact format:\nVERDICT: [INCOMPLETE or COMPLETE]\nCONFIDENCE: [0.0-1.0]\nMISSING_ITEM: [what the user asked for that the action does not address, or NONE]\nREASONING: [one sentence]\n\nIf the number in question is unrelated to the request (a zip code fragment,\nan already-resolved detail, or a different valid identifier for an item that\nIS addressed elsewhere in the action), respond COMPLETE."""'

path = "src/sentinel/judge.py"
content = open(path).read()
if old not in content:
    print("OLD TEXT NOT FOUND -- stopping, paste your current judge.py so I can check.")
else:
    content = content.replace(old, new, 1)
    open(path, "w").write(content)
    print("prompt strengthened with worked example, patched successfully")
