"""Turn an IncidentReport into artifacts engineers actually use:
  1. Markdown incident report (paste into Jira/Slack)
  2. Pytest regression test (merge into CI)
  3. Eval spec YAML (portable check definition)

Every production failure becomes a permanent test. That closure — incident ->
localized root cause -> regression gate — is the whole product thesis.
"""
from __future__ import annotations

import json
from datetime import date

import yaml

from .schema import IncidentReport, StepType, Trace


def render_markdown(report: IncidentReport, trace: Trace) -> str:
    lines = [f"# Incident Report — `{report.trace_id}`", ""]
    lines.append(f"**Date:** {date.today().isoformat()}  |  **Verdict:** {report.verdict}")
    lines.append("")
    user = next((s for s in trace.steps if s.type == StepType.USER), None)
    if user:
        lines.append(f"**User request:** {str(user.input)[:200]}")
        lines.append("")
    if report.localization is None:
        lines.append("No deterministic findings. Trace appears healthy.")
        return "\n".join(lines)

    loc = report.localization
    lines.append("## Root cause (first bad decision)")
    lines.append("")
    lines.append(f"**Step {loc.root_step_index} — {loc.root_category}** "
                 f"(severity: {loc.root_finding.severity.value}, confidence: {loc.root_finding.confidence:.2f}, "
                 f"detector: `{loc.root_finding.detector}`)")
    lines.append("")
    for ev in loc.root_finding.evidence:
        lines.append(f"- {ev}")
    lines.append("")
    lines.append(f"**Fix location:** {loc.fix_location}")
    lines.append("")
    lines.append(f"**Recommended fix:** {loc.root_finding.fix_hint}")
    if loc.do_not_modify:
        lines.append("")
        lines.append(f"**Do not modify:** {', '.join(loc.do_not_modify)}")
    if loc.propagation:
        lines.append("")
        lines.append("## Propagation (consequences of the root, not separate bugs)")
        lines.append("")
        for f in loc.propagation:
            lines.append(f"- Step {f.step_index} — **{f.category}**: {f.evidence[0]}")
    lines.append("")
    lines.append("## Timeline")
    lines.append("")
    for s in trace.steps:
        marker = " ⟵ ROOT CAUSE" if s.index == loc.root_step_index else ""
        label = s.name or s.type.value
        lines.append(f"- `[{s.index}]` {s.type.value}: {label}{marker}")
    return "\n".join(lines)


def render_pytest(report: IncidentReport, trace: Trace) -> str:
    """A regression test that re-runs Sentinel's deterministic analysis on a fresh
    trace produced by the same query, and fails if the same category recurs."""
    loc = report.localization
    cat = loc.root_category if loc else "none"
    user = next((s for s in trace.steps if s.type == StepType.USER), None)
    query = json.dumps(str(user.input) if user else "")
    exp = trace.expectations.model_dump() if trace.expectations else {}
    return f'''"""Auto-generated by Sentinel from incident {report.trace_id}.

Regression gate: the failure category `{cat}` must never recur for this query.
Wire `run_agent_and_capture_trace` to your agent harness.
"""
import json
import pytest

from sentinel.parser import parse_generic
from sentinel.localizer import analyze

QUERY = {query}
EXPECTATIONS = {json.dumps(exp, indent=2)}
FORBIDDEN_CATEGORY = "{cat}"


def run_agent_and_capture_trace(query: str) -> dict:
    raise NotImplementedError("Wire this to your agent + trace capture.")


@pytest.mark.regression
def test_incident_{report.trace_id.replace("-", "_")}_does_not_recur():
    raw = run_agent_and_capture_trace(QUERY)
    raw.setdefault("expectations", EXPECTATIONS)
    result = analyze(parse_generic(raw))
    recurred = [f for f in result.all_findings if f.category == FORBIDDEN_CATEGORY]
    assert not recurred, (
        f"Incident {report.trace_id} recurred: "
        + "; ".join(e for f in recurred for e in f.evidence)
    )
'''


def render_eval_spec(report: IncidentReport, trace: Trace) -> str:
    loc = report.localization
    user = next((s for s in trace.steps if s.type == StepType.USER), None)
    spec = {
        "eval": f"regression-{report.trace_id}",
        "origin": "sentinel-incident",
        "query": str(user.input) if user else None,
        "assertions": {
            "forbid_failure_category": loc.root_category if loc else None,
            "expected_tools": trace.expectations.expected_tools if trace.expectations else [],
            "forbidden_tools": trace.expectations.forbidden_tools if trace.expectations else [],
            "grounding": "all hard values in answer must appear in observed evidence",
        },
        "severity_if_failed": loc.root_finding.severity.value if loc else None,
    }
    return yaml.safe_dump(spec, sort_keys=False)
